[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pygame-builtins"
version = "1.0.0"
dependencies = ["pygame-ce", "tomlkit"]

[project.optional-dependencies]
test = ["pytest"]
dev = ["pytest", "black"]

[pytest]
testpaths = "tests"
